create table
  public."anomalies" (
    id bigint generated by default as identity,
    content text null,
    "ticId" text null,
    anomalyType text null,
    type text null,
    avatar_url text null,
    created_at timestamp with time zone not null default now(),
    deepnote text null,
    lightkurve text null,
    configuration jsonb null, -- Adding the new JSONB column
    constraint basePlanets_pkey primary key (id)
) tablespace pg_default;