import { Telescope, Leaf, CloudSun, Globe, Target, Zap, Eye, Search, Wind, Shield, DrillIcon } from "lucide-react"
import type { Structure, Project } from "./types"

export const structures: Structure[] = [
  {
    name: "Refracting Telescope",
    icon: Telescope,
    description: "Browse & classify space-based observations & classifications",
    specialty: "Deep Space Explorer",
    difficulty: "Beginner",
    bgGradient: "from-blue-500/10 to-cyan-500/10",
    iconColor: "text-blue-600",
    inventoryItemId: 3103,
    status: "operational",
    powerLevel: 87,
    systemVersion: "v3.2.1",
  },
  {
    name: "Biodome",
    icon: Leaf,
    description: "For xenobiologists studying alien life forms",
    specialty: "Life Sciences Specialist",
    difficulty: "Intermediate",
    bgGradient: "from-green-500/10 to-emerald-500/10",
    iconColor: "text-green-600",
    inventoryItemId: 3104,
    status: "operational",
    powerLevel: 92,
    systemVersion: "v2.8.5",
  },
  {
    name: "Atmospheric Probe",
    icon: CloudSun,
    description: "For climatologists analyzing extraterrestrial atmospheres",
    specialty: "Climate Researcher",
    difficulty: "Advanced",
    bgGradient: "from-purple-500/10 to-primary/10",
    iconColor: "text-primary",
    inventoryItemId: 3105,
    status: "limited",
    powerLevel: 64,
    systemVersion: "v4.0.2",
  },
  {
    name: "SeisCAM",
    icon: DrillIcon,
    description: "For geologists exploring exoplanet surfaces and oceans",
    specialty: "Geologists",
    difficulty: "Beginner",
    bgGradient: 'from-green-500 to-primary/10',
    iconColor: 'text-blue-400',
    inventoryItemId: 3107,
    status: "operational",
    powerLevel: 100,
    systemVersion: 'v1.0.1',
  },
]

export const projects: Record<string, Project[]> = {
  "Refracting Telescope": [
    {
      name: "Planet Hunting",
      description: "Discover real planets in our galactic community",
      identifier: "telescope-tess",
      sourceLink: "https://www.zooniverse.org/projects/mschwamb/planet-hunters-ngts",
      icon: Globe,
      techId: 3103,
      tutorialMission: 3000001,
      activeStructure: 3103,
      status: "active",
      difficulty: 2,
      estimatedTime: "4-6 hrs",
    },
    {
      name: "Asteroid Detection",
      description: "Discover new asteroids everyday in your telescope's data",
      identifier: "telescope-minorPlanet",
      sourceLink: "https://www.zooniverse.org/projects/fulsdavid/the-daily-minor-planet",
      icon: Target,
      techId: 3103,
      tutorialMission: 20000004,
      activeStructure: 3103,
      status: "active",
      difficulty: 3,
      estimatedTime: "2-3 hrs",
    },
    {
      name: "Sunspot observations",
      description: "Help diagnose our sun's health problems and behaviour",
      identifier: "telescope-sunspots",
      sourceLink: "https://www.zooniverse.org/projects/teolixx/sunspot-detectives",
      icon: Zap,
      techId: 3103,
      tutorialMission: 3000002,
      activeStructure: 3103,
      status: "maintenance",
      difficulty: 4,
      estimatedTime: "5-8 hrs",
    },
  ],
  "SeisCAM": [
    {
      name: "AI4Mars",
      description:
        "Label real Mars rover images to help train autonomous navigation systems and improve future Martian exploration.",
      identifier: "seiscam-ai4mars",
      sourceLink: "https://www.zooniverse.org/projects/hiroc/ai4mars",
      icon: Search,
      techId: 3107,
      tutorialMission: 3000021,
      activeStructure: 3107,
      status: "active",
      difficulty: 3,
      estimatedTime: "4-6 hrs",
    },
    {
      name: "Planet Four",
      description:
        "Help identify wind-driven features on Mars' south pole to better understand Martian climate patterns.",
      identifier: "seiscam-planetFour",
      sourceLink: "https://www.zooniverse.org/projects/mschwamb/planet-four",
      icon: Wind,
      techId: 3107,
      tutorialMission: 3000022,
      activeStructure: 3107,
      status: "active",
      difficulty: 2,
      estimatedTime: "3-5 hrs",
    },
  ],
  Biodome: [
    {
      name: "Wildwatch Burrowing Owls",
      description:
        "Document and understand the developmental milestones of Otey Mesa burrowing owls through your observation satellites",
      identifier: "zoodex-burrowingOwl",
      sourceLink: "zooniverse.org/projects/sandiegozooglobal/wildwatch-burrowing-owl/",
      icon: Eye,
      techId: 3104,
      tutorialMission: 3000004,
      activeStructure: 3104,
      status: "active",
      difficulty: 2,
      estimatedTime: "3-5 hrs",
    },
    {
      name: "Iguanas from Above",
      description: "Help us count Galapagos Marine Iguanas from aerial photographs taken by your satellite network",
      identifier: "zoodex-iguanasFromAbove",
      sourceLink: "https://www.zooniverse.org/projects/andreavarela89/iguanas-from-above",
      icon: Search,
      techId: 3104,
      tutorialMission: 3000004,
      activeStructure: 3104,
      status: "active",
      difficulty: 1,
      estimatedTime: "2-4 hrs",
    },
  ],
  "Atmospheric Probe": [
    {
      name: "Martian Cloud Survey",
      description: "Model cloud behaviour on Mars (and similar exoplanet candidates)",
      identifier: "lidar-martianClouds",
      sourceLink: "https://www.zooniverse.org/projects/marek-slipski/cloudspotting-on-mars",
      icon: Wind,
      techId: 3105,
      tutorialMission: 3000010,
      activeStructure: 3105,
      status: "active",
      difficulty: 3,
      estimatedTime: "4-7 hrs",
    },
    {
      name: "Vortex Hunter",
      description: "Identify and manipulate features & fluid dynamics in gaseous planets like Jupiter",
      identifier: "lidar-jovianVortexHunter",
      sourceLink: "zooniverse.org/projects/ramanakumars/jovian-vortex-hunter/",
      icon: Shield,
      techId: 3105,
      tutorialMission: 20000007,
      activeStructure: 3105,
      status: "offline",
      difficulty: 5,
      estimatedTime: "6-10 hrs",
    },
  ],
};