export const milestones = [
    {
        weekStart: '2025-07-20',
        data: [
            {
                name: "Verify other users' discoveries and get some of the earnings in return",
                structure: "Telescope",
                group: "Astronomy",
                icon: 'Telescope',
                extendedDescription: 'Check your notifications to see if someone has made a classification and requested support',
                xp: 1,
                completionInfo: '',
                rewardInfo: '',
                table: 'votes',
                field: 'vote_type',
                value: 'up',
                requiredCount: 2,
            },
            {
                name: "Propose 3 planet candidates",
                structure: "Telescope",
                group: "Astronomy",
                icon: "Telescope",
                extendedDescription: 'Deploy your telescope and find new planets!',
                xp: 1,
                completionInfo: '',
                rewardInfo: '',
                table: 'comments',
                field: 'surveyor',
                value: 'TRUE',
                requiredCount: 1,
            },
        ],
    },
    {
        weekStart: '2025-07-06',
        data: [
            {
                name: "Verify other users' discoveries and get some of the earnings in return",
                structure: "Telescope",
                group: "Astronomy",
                icon: 'Telescope',
                extendedDescription: ',',
                xp: 1,
                completionInfo: '',
                rewardInfo: '',
                table: 'votes',
                field: 'vote_type',
                value: 'up',
                requiredCount: 2,
            },
            {
                name: "Contribute to someone else's discovery by commenting",
                structure: "Telescope",
                group: "Astronomy",
                icon: "Telescope",
                extendedDescription: '',
                xp: 1,
                completionInfo: '',
                rewardInfo: '',
                table: 'comments',
                field: 'surveyor',
                value: 'TRUE',
                requiredCount: 1,
            },
        ],
    },
    {
        weekStart: '2025-06-29',
        data: [
            {
                name: "Contribute to someone else's discovery by commenting",
                structure: "Telescope",
                group: "Astronomy",
                icon: "Telescope",
                extendedDescription: '',
                xp: 1,
                completionInfo: '',
                rewardInfo: '',
                table: 'comments',
                field: 'surveyor',
                value: 'TRUE',
                requiredCount: 1,
            },
            {
                name: "Train our automatons - discover 3 obstacles",
                structure: "WeatherBalloon",
                group: "Meteorology",
                icon: "SnowflakeIcon",
                extendedDescription: '',
                xp: 3,
                completionInfo: '',
                rewardInfo: '',
                table: "classifications",
                field: 'classificationtype',
                value: 'automaton-aiForMars',
                requiredCount: 3,
            },
        ],
    },
            {
        weekStart: '2025-06-15',
        data: [
            {
                name: 'Propose 3 planet candidates',
                structure: "Telescope",
                group: 'Astronomy',
                icon: "Telescope",
                extendedDescription: '',
                xp: 3,
                completionInfo: '',
                rewardInfo: '',
                table: "classifications",
                field: "classificationtype",
                value: "planet",
                requiredCount: 3,
            },
            {
                name: 'Review satellite data',
                structure: "WeatherBalloon",
                group: 'Meteorology',
                icon: "SnowflakeIcon",
                extendedDescription: '',
                xp: 2,
                completionInfo: '',
                rewardInfo: '',
                table: "classifications",
                field: "classificationtype",
                value: "satellite-planetFour",
                requiredCount: 2,
            },
        ],
    },
        {
        weekStart: '2025-06-06',
        data: [
            {
                name: 'Propose 5 planet candidates',
                structure: "Telescope",
                group: 'Astronomy',
                icon: "Telescope",
                extendedDescription: '',
                xp: 5,
                completionInfo: '',
                rewardInfo: '',
                table: "classifications",
                field: "classificationtype",
                value: "planet",
                requiredCount: 5,
            },
        ],
    },
    {
        weekStart: '2025-05-18',
        data: [
            {
                name: 'Collect animals around you',
                structure: "Greenhouse",
                // group: 'Meteorology',
                group: 'Bioloy',
                icon: "PawPrintIcon",
                extendedDescription: '',
                xp: 2,
                completionInfo: '',
                rewardInfo: '',
                table: "uploads",
                field: "source",
                value: "Webcam",
                requiredCount: 1,
            },
            {
                name: 'Make 1 Temperature Classification',
                structure: 'Telescope',
                group: 'Astronomy',
                icon: "Telescope",
                extendedDescription: "",
                xp: 3,
                completionInfo: '',
                rewardInfo: '',
                table: "comments",
                field: "category",
                value: "Temperature",
                requiredCount: 1,
            },
            {
                name: 'Retrieve satellite images of your planets',
                structure: 'WeatherBalloon',
                group: 'Astronomy',
                icon: "Telescope",
                extendedDescription: "",
                xp: 3,
                completionInfo: '',
                rewardInfo: '',
                table: "classifications",
                field: "classificationtype",
                value: "satellite-planetFour",
                requiredCount: 1,
            },
        ],
    },
    {
        weekStart: '2025-04-28',
        data: [
            {
                name: 'Discover 2 planets',
                structure: "Telescope",
                group: 'Astronomy',
                icon: "PawPrintIcon",
                extendedDescription: '',
                xp: 2,
                completionInfo: '',
                rewardInfo: '',
                table: "classifications",
                field: "classificationtype",
                value: "planet",
                requiredCount: 2,
            },
            // {
            //     name: "Create a storm on a gas giant",
            //     structure: "WeatherBalloon",
            //     icon: "SnowflakeIcon",
            //     xp: 1,
            //     extendedDescription: "",
            //     completionInfo: "",
            //     rewardInfo: "",
            //     table: 'events',
            //     field: 'eventtype',
            //     value: 'vortex-storm',
            //     requiredCount: 1,
            // },
            // {
            //     name: 'Make 3 Temperature Classifications',
            //     structure: 'Telescope',
            //     icon: "Telescope",
            //     extendedDescription: "",
            //     xp: 3,
            //     completionInfo: '',
            //     rewardInfo: '',
            //     table: "comments",
            //     field: "category",
            //     value: "Temperature",
            //     requiredCount: 3,
            // },
        ],
    },
    {
        weekStart: '2025-04-21',
        data: [
            // {
            //     name: 'Make 3 Temperature Classifications',
            //     structure: 'Telescope',
            //     icon: "Telescope",
            //     extendedDescription: "",
            //     xp: 3,
            //     completionInfo: '',
            //     rewardInfo: '',
            //     table: "comments",
            //     field: "category",
            //     value: "Temperature",
            //     requiredCount: 3,
            // },
            // {
            //     name: 'Discover 2 planets',
            //     structure: "Telescope",
            //     icon: "PawPrintIcon",
            //     extendedDescription: '',
            //     xp: 2,
            //     completionInfo: '',
            //     rewardInfo: '',
            //     table: "classifications",
            //     field: "classificationtype",
            //     value: "planet",
            //     requiredCount: 2,
            // },
            {
                name: "Create a storm on a gas giant",
                structure: "WeatherBalloon",
                group: 'Meteorology',
                icon: "SnowflakeIcon",
                xp: 1,
                extendedDescription: "",
                completionInfo: "",
                rewardInfo: "",
                table: 'events',
                field: 'eventtype',
                value: 'vortex-storm',
                requiredCount: 1,
            },
        ],
    },
    {
        weekStart: '2025-04-14',
        data: [
            // {
            //     name: 'Make 3 Temperature Classifications',
            //     structure: 'Telescope',
            //     icon: "Telescope",
            //     extendedDescription: "",
            //     xp: 3,
            //     completionInfo: '',
            //     rewardInfo: '',
            //     table: "comments",
            //     field: "category",
            //     value: "Temperature",
            //     requiredCount: 3,
            // },
            {
                name: 'Discover 2 planets',
                structure: "Telescope",
                group: 'Astronomy',
                icon: "PawPrintIcon",
                extendedDescription: '',
                xp: 2,
                completionInfo: '',
                rewardInfo: '',
                table: "classifications",
                field: "classificationtype",
                value: "planet",
                requiredCount: 2,
            },
            // {
            //     name: "Create a storm on a gas giant",
            //     structure: "WeatherBalloon",
            //     icon: "SnowflakeIcon",
            //     xp: 1,
            //     extendedDescription: "",
            //     completionInfo: "",
            //     rewardInfo: "",
            //     table: 'events',
            //     field: 'eventtype',
            //     value: 'vortex-storm',
            //     requiredCount: 1,
            // },
        ],
    },
    // {
    //     weekStart: "2025-02-18",
    //     data: [
    //         { 
    //             name: "Find 3 desert creatures", 
    //             structure: "Greenhouse", 
    //             icon: "PawPrintIcon",
    //             extendedDescription: "",
    //             xp: null,
    //             completionInfo: "",
    //             rewardInfo: ""
    //         },
    //         { 
    //             name: "Find ice on a planet", 
    //             structure: "WeatherBalloon", 
    //             icon: "SnowflakeIcon",
    //             extendedDescription: "",
    //             xp: null,
    //             completionInfo: "",
    //             rewardInfo: ""
    //         },
    //         { 
    //             name: "Find a planet in the habitable zone", 
    //             structure: "Telescope", 
    //             icon: "GlassWaterIcon",
    //             extendedDescription: "",
    //             xp: null,
    //             completionInfo: "",
    //             rewardInfo: ""
    //         },
    //     ],
    // },
    // {
    //     weekStart: "2025-02-11",
    //     data: [
    //         { 
    //             name: "Discover a new microbial species", 
    //             structure: "Greenhouse", 
    //             icon: "PawPrintIcon",
    //             extendedDescription: "",
    //             xp: null,
    //             completionInfo: "",
    //             rewardInfo: ""
    //         },
    //         { 
    //             name: "Detect a storm with a weather balloon", 
    //             structure: "WeatherBalloon", 
    //             icon: "SnowflakeIcon",
    //             extendedDescription: "",
    //             xp: null,
    //             completionInfo: "",
    //             rewardInfo: ""
    //         },
    //         { 
    //             name: "Observe a distant exoplanet", 
    //             structure: "Telescope", 
    //             icon: "GlassWaterIcon",
    //             extendedDescription: "",
    //             xp: null,
    //             completionInfo: "",
    //             rewardInfo: ""
    //         },
    //     ],
    // },
];

export const communityMilestones = [
    {
        weekStart: "2025-02-18",
        data: [
            { 
                name: "Discover 100 desert creatures", 
                structure: "Greenhouse", 
                icon: "PawPrintIcon",
                extendedDescription: "As the community explores, they find 100 desert creatures across planets.",
                xp: null,
                completionInfo: "The community achieves a combined total of 100 desert creatures discovered.",
                rewardInfo: "Unlocks the 'Desert Explorer' badge for all players."
            },
            { 
                name: "Discover 50 ice formations on planets", 
                structure: "WeatherBalloon", 
                icon: "SnowflakeIcon",
                extendedDescription: "The community explores icy terrains, discovering 50 ice formations.",
                xp: null,
                completionInfo: "A total of 50 ice formations discovered by the community.",
                rewardInfo: "Unlocks the 'Arctic Adventurer' badge for all players."
            },
            { 
                name: "Observe 75 planets in the habitable zone", 
                structure: "Telescope", 
                icon: "GlassWaterIcon",
                extendedDescription: "Through collective efforts, the community identifies 75 planets within habitable zones.",
                xp: null,
                completionInfo: "The community successfully identifies 75 habitable planets.",
                rewardInfo: "Unlocks the 'Habitable Zone Pioneer' badge for all players."
            },
        ],
    },
    // {
    //     weekStart: "2025-02-11",
    //     data: [
    //         { 
    //             name: "Community discovers 50 new microbial species", 
    //             structure: "Greenhouse", 
    //             icon: "PawPrintIcon",
    //             extendedDescription: "The community works together to discover a total of 50 new microbial species.",
    //             xp: null,
    //             completionInfo: "The community has collectively discovered 50 microbial species.",
    //             rewardInfo: "Unlocks the 'Microbial Pioneer' badge for all players."
    //         },
    //         { 
    //             name: "Community detects 30 storms with weather balloons", 
    //             structure: "WeatherBalloon", 
    //             icon: "SnowflakeIcon",
    //             extendedDescription: "The community makes groundbreaking discoveries, detecting 30 storms across planets.",
    //             xp: null,
    //             completionInfo: "30 storms detected by the collective community.",
    //             rewardInfo: "Unlocks the 'Storm Tracker' badge for all players."
    //         },
    //         { 
    //             name: "Community observes 100 distant exoplanets", 
    //             structure: "Telescope", 
    //             icon: "GlassWaterIcon",
    //             extendedDescription: "The community works to observe and catalog 100 distant exoplanets.",
    //             xp: null,
    //             completionInfo: "A total of 100 exoplanets observed by the community.",
    //             rewardInfo: "Unlocks the 'Exoplanet Explorer' badge for all players."
    //         },
    //     ],
    // },
];
