create table
    public.zoo (
        id bigint generated by default as identity,
        author uuid not null,
        owner uuid not null, /* Users may be able to transfer entities later */
        location bigint not null, /* Points to a greenhouse/bio station */
        configuration jsonb null,
        uploaded bigint not null,
        content text null,
        created_at timestamp with time zone not null default now(),
        file_url text not null,
        constraint zoo_pkey primary key (id),
        constraint zoo_author_fkey foreign key (author) references profiles (id) on delete cascade,
        constraint zoo_location_fkey foreign key (location) references inventory (id) on delete cascade,
        constraint zoo_uploaded_fkey foreign key (uploaded) references uploads (id) on delete cascade
    ) tablespace pg_default