/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vGoyZOai47K
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { ResponsiveLine } from "@nivo/line"
import { ScrollArea } from "@/components/ui/scroll-area"

export function RoverWindow() {
  return (
    <div className="bg-[#333333] text-white p-8 flex flex-col md:flex-row md:space-x-8 rounded-lg max-w-screen-xl mx-auto">
      <div className="flex-1">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-xl font-bold">End Operation</h1>
          <Button className="text-white" variant="ghost">
            ...
          </Button>
        </div>
        <div className="mb-6">
          <h2 className="text-2xl font-bold mb-2">Mars 2020 Perseverance Rover</h2>
          <div className="flex justify-between">
            <div>
              <h3 className="font-semibold">Time</h3>
              <p>Sunrise: 6:05 am</p>
              <p>Sunset: 9:37 pm</p>
            </div>
            <div>
              <h3 className="font-semibold">Pressure</h3>
              <p>16.12</p>
            </div>
            <div>
              <h3 className="font-semibold">Oxygen</h3>
              <p>0.027 %</p>
            </div>
            <div>
              <h3 className="font-semibold">Temperature</h3>
              <p>-35°C</p>
            </div>
          </div>
        </div>
        <div className="mb-6">
          <h3 className="font-semibold mb-2">ROVER STATUS</h3>
          <div className="flex justify-between">
            <div>
              <h4 className="font-semibold">Battery</h4>
              <div className="flex">
                <BatteryFullIcon className="w-5 h-5" />
                <BatteryFullIcon className="w-5 h-5" />
                <BatteryFullIcon className="w-5 h-5" />
                <BatteryFullIcon className="w-5 h-5" />
                <BatteryFullIcon className="w-5 h-5" />
              </div>
            </div>
            <div>
              <h4 className="font-semibold">Trunk</h4>
              <div className="flex">
                <CircleIcon className="w-5 h-5" />
                <CircleIcon className="w-5 h-5" />
                <CircleIcon className="w-5 h-5" />
                <CircleIcon className="w-5 h-5" />
                <CircleIcon className="w-5 h-5" />
              </div>
            </div>
            <div>
              <h4 className="font-semibold">Delay</h4>
              <p>40 min</p>
            </div>
          </div>
        </div>
        <div className="mb-6">
          <h3 className="font-semibold mb-2">Cameras</h3>
          <p>All Report Online</p>
        </div>
        <div className="flex justify-center">
          <CurvedlineChart className="w-[200px] h-[200px]" />
        </div>
      </div>
      <div className="flex-1">
        <div className="grid grid-cols-3 gap-4 mb-6">
          <img
            alt="Rover Image"
            className="rounded-lg"
            height="100"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/100",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Rover Image"
            className="rounded-lg"
            height="100"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/100",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Rover Image"
            className="rounded-lg"
            height="100"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/100",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Rover Image"
            className="rounded-lg"
            height="100"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/100",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Rover Image"
            className="rounded-lg"
            height="100"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/100",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Rover Image"
            className="rounded-lg"
            height="100"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/100",
              objectFit: "cover",
            }}
            width="100"
          />
        </div>
        <div className="bg-[#222222] p-4 rounded-lg mb-6">
          <h3 className="font-semibold mb-2">Results</h3>
          <ScrollArea className="space-y-2 h-48">
            <p>
              <CheckIcon className="w-4 h-4" /> Sample taken
            </p>
            <p>
              <XIcon className="w-4 h-4" /> Error in Cam 7
            </p>
            <p>
              <CheckIcon className="w-4 h-4" /> Cam 7 selfixed
            </p>
            <p>
              <CheckIcon className="w-4 h-4" /> Picture taken
            </p>
            <p>
              <CheckIcon className="w-4 h-4" /> Sample taken
            </p>
            <p>
              <CheckIcon className="w-4 h-4" /> Rover moved
            </p>
          </ScrollArea>
          <Button className="mt-4" variant="outline">
            Download All
          </Button>
        </div>
        <div className="flex justify-center">
          <CurvedlineChart className="w-[200px] h-[200px]" />
        </div>
      </div>
    </div>
  )
}

function BatteryFullIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="10" x="2" y="7" rx="2" ry="2" />
      <line x1="22" x2="22" y1="11" y2="13" />
      <line x1="6" x2="6" y1="11" y2="13" />
      <line x1="10" x2="10" y1="11" y2="13" />
      <line x1="14" x2="14" y1="11" y2="13" />
    </svg>
  )
}


function CheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function CircleIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
    </svg>
  )
}


function CurvedlineChart(props: any) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        curve="monotoneX"
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}


function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
