#!/usr/bin/env node
// Generates the Worker's route tables from src/app (SSC-31):
//   workers/app/src/generated/api-routes.ts   every src/app/api/**/route.ts
//   workers/app/src/generated/page-routes.ts  every dynamic page.tsx, mapped
//                                             to its exported placeholder HTML
// `--check` exits 1 when the committed files are stale (run in CI).
import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(fileURLToPath(import.meta.url), "..", "..", "..");
const appDir = join(root, "src", "app");
const outDir = join(root, "workers", "app", "src", "generated");
const PLACEHOLDER = "__static__";

function walk(dir, name) {
  const found = [];
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) found.push(...walk(full, name));
    else if (entry === name) found.push(full);
  }
  return found;
}

// Route groups "(x)" and private folders "_x" never appear in the URL.
function urlSegments(file) {
  return relative(appDir, file)
    .split(sep)
    .slice(0, -1)
    .filter((s) => !(s.startsWith("(") && s.endsWith(")")));
}

function toPattern(segments) {
  return segments.map((s) => {
    const catchAll = s.match(/^\[\.\.\.(\w+)\]$/);
    if (catchAll) return { kind: "rest", name: catchAll[1] };
    const param = s.match(/^\[(\w+)\]$/);
    if (param) return { kind: "param", name: param[1] };
    return { kind: "literal", value: s };
  });
}

// Most literal segments first, so /planets/edit/:id beats /planets/:a/:b.
const specificity = (p) => p.filter((s) => s.kind === "literal").length * 100 - p.filter((s) => s.kind === "rest").length;

const header = "// Generated by scripts/cloudflare/generate-routes.mjs. Do not edit.\n";

const apiRoutes = walk(join(appDir, "api"), "route.ts")
  .map((file) => ({ file, pattern: toPattern(urlSegments(file)) }))
  .sort((a, b) => specificity(b.pattern) - specificity(a.pattern) || a.file.localeCompare(b.file));

let api = header + 'import type { RouteModule } from "../routeTypes";\n';
apiRoutes.forEach((r, i) => {
  const spec = relative(join(outDir), r.file).split(sep).join("/").replace(/\.ts$/, "");
  api += `import * as r${i} from "${spec}";\n`;
});
api += "\nexport const apiRoutes: Array<{ pattern: string; segments: RouteSegment[]; module: RouteModule }> = [\n";
apiRoutes.forEach((r, i) => {
  api += `  { pattern: ${JSON.stringify("/" + urlSegments(r.file).join("/"))}, segments: ${JSON.stringify(r.pattern)}, module: r${i} as unknown as RouteModule },\n`;
});
api += "];\n\nexport type RouteSegment =\n  | { kind: \"literal\"; value: string }\n  | { kind: \"param\"; name: string }\n  | { kind: \"rest\"; name: string };\n";

const dynamicPages = walk(appDir, "page.tsx")
  .map((file) => ({ file, segments: urlSegments(file) }))
  .filter((p) => p.segments.some((s) => s.startsWith("[")))
  .map((p) => ({ ...p, pattern: toPattern(p.segments) }))
  .sort((a, b) => specificity(b.pattern) - specificity(a.pattern) || a.file.localeCompare(b.file));

let pages = header + 'import type { RouteSegment } from "./api-routes";\n\n';
pages += `export const STATIC_PARAM_PLACEHOLDER = ${JSON.stringify(PLACEHOLDER)};\n\n`;
pages += "// Each dynamic page is exported once, with every param set to the placeholder.\n";
pages += "export const dynamicPages: Array<{ pattern: string; segments: RouteSegment[]; asset: string }> = [\n";
for (const p of dynamicPages) {
  const asset = "/" + p.segments.map((s) => (s.startsWith("[") ? PLACEHOLDER : s)).join("/");
  pages += `  { pattern: ${JSON.stringify("/" + p.segments.join("/"))}, segments: ${JSON.stringify(p.pattern)}, asset: ${JSON.stringify(asset)} },\n`;
}
pages += "];\n";

const outputs = { "api-routes.ts": api, "page-routes.ts": pages };
const check = process.argv.includes("--check");
let stale = false;
mkdirSync(outDir, { recursive: true });
for (const [name, content] of Object.entries(outputs)) {
  const target = join(outDir, name);
  let current = null;
  try {
    current = readFileSync(target, "utf8");
  } catch {}
  if (current === content) continue;
  if (check) {
    console.error(`${relative(root, target)} is stale; run yarn cf:routes`);
    stale = true;
  } else {
    writeFileSync(target, content);
    console.log(`wrote ${relative(root, target)}`);
  }
}
process.exit(stale ? 1 : 0);
