create table public.comments (
  id bigint generated by default as identity,
  created_at timestamp with time zone not null default now(),
  content text not null,
  author uuid not null,  
  classification_id bigint not null,  
  parent_comment_id bigint null,  
  configuration jsonb null,  
  constraint comments_pkey primary key (id),
  constraint comments_author_fkey foreign key (author) references profiles (id),
  constraint comments_classification_fkey foreign key (classification_id) references classifications (id),
  constraint comments_parent_comment_fkey foreign key (parent_comment_id) references comments (id) 
);