CREATE TABLE public.votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES profiles(id),
    classification_id BIGINT NOT NULL REFERENCES classifications(id),
    anomaly_id BIGINT NOT NULL REFERENCES anomalies(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, classification_id)
);