CREATE TABLE
    public."mineralDeposits" (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        anomaly BIGINT NULL,
        owner UUID NULL,
        mineralConfiguration JSONB NULL,
        CONSTRAINT mineralDeposits_pkey PRIMARY KEY (id),
        CONSTRAINT mineralDeposits_anomaly_fkey FOREIGN KEY (anomaly) REFERENCES anomalies (id),
        CONSTRAINT mineralDeposits_owner_fkey FOREIGN KEY (owner) REFERENCES profiles (id)
) TABLESPACE pg_default;