create table
  public.tool_interactions (
    id bigint generated by default as identity,
    author uuid not null,
    datetime timestamp with time zone not null default now(),
    linked_anom bigint null,
    route bigint null,
    constraint tool_interactions_pkey primary key (id),
    constraint tool_interactions_author_fkey foreign key (author) references profiles (id) on delete cascade,
    constraint tool_interactions_linked_anom_fkey foreign key (linked_anom) references linked_anomalies (id) on delete cascade,
    constraint tool_interactions_route_fkey foreign key (route) references routes (id) on delete cascade
  ) tablespace pg_default;

create index if not exists idx_tool_interactions_author on public.tool_interactions using btree (author) tablespace pg_default;

create index if not exists idx_tool_interactions_datetime on public.tool_interactions using btree (datetime desc) tablespace pg_default;

create index if not exists idx_tool_interactions_linked_anom on public.tool_interactions using btree (linked_anom) tablespace pg_default;

create index if not exists idx_tool_interactions_route on public.tool_interactions using btree (route) tablespace pg_default;