-- Create routes table
CREATE TABLE IF NOT EXISTS "public"."routes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "author" uuid NOT NULL,
    "routeConfiguration" jsonb,
    "timestamp" timestamp with time zone DEFAULT now() NOT NULL,
    "location" bigint NOT NULL,
    
    -- Foreign key constraints
    CONSTRAINT "routes_author_fkey" 
        FOREIGN KEY ("author") 
        REFERENCES "public"."profiles"("id") 
        ON DELETE CASCADE,
        
    CONSTRAINT "routes_location_fkey" 
        FOREIGN KEY ("location") 
        REFERENCES "public"."anomalies"("id") 
        ON DELETE CASCADE
);

-- Set table ownership
ALTER TABLE "public"."routes" OWNER TO "postgres";

-- Add helpful comments
COMMENT ON TABLE "public"."routes" IS 'Stores route configurations created by users for specific anomaly locations';
COMMENT ON COLUMN "public"."routes"."author" IS 'User who created this route';
COMMENT ON COLUMN "public"."routes"."routeConfiguration" IS 'JSON configuration data for the route';
COMMENT ON COLUMN "public"."routes"."timestamp" IS 'When the route was created';
COMMENT ON COLUMN "public"."routes"."location" IS 'Anomaly location where this route applies';

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS "idx_routes_author" ON "public"."routes" ("author");
CREATE INDEX IF NOT EXISTS "idx_routes_location" ON "public"."routes" ("location");
CREATE INDEX IF NOT EXISTS "idx_routes_timestamp" ON "public"."routes" ("timestamp" DESC);
