create table public.events (
  id bigint generated by default as identity not null,
  location bigint not null,
  classification_location bigint not null,
  type text not null,
  configuration jsonb not null,
  time timestamp with time zone not null default now(),
  completed boolean not null default false,
  constraint events_pkey primary key (id),
  constraint events_classification_location_fkey foreign KEY (classification_location) references classifications (id) on delete CASCADE,
  constraint events_location_fkey foreign KEY (location) references anomalies (id) on delete CASCADE
) TABLESPACE pg_default;