name: Delete Push Anomaly Log

on:
  schedule:
    # Run at 00:00 AEST every Sunday (AEST is UTC+10, so 14:00 UTC Saturday)
    - cron: '0 14 * * 6'
  workflow_dispatch:

jobs:
  delete-push-anomaly-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod tidy
      - name: Delete push anomaly log
        env:
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: go run scripts/delete_push_anomaly_log.go
