name: Notify Users of Unclassified Discoveries

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  push:
    branches: [ main, master, SSG-270-actionpatch​ ]
  workflow_dispatch: # Allow manual triggering

jobs:
  notify-discoveries:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Send discovery notifications
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        NEXT_PUBLIC_VAPID_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_VAPID_PUBLIC_KEY }}
        VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
      run: node scripts/notify-unclassified-discoveries.js
