name: Send Push Notifications

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes UTC
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jobs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Run push notification job
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          NEXT_PUBLIC_VAPID_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_VAPID_PUBLIC_KEY }}
          VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
        run: go run send_push_notifications.go