name: Unlock SolarHealth Anomalies

on:
  schedule:
    # Run every 24 hours
    - cron: '0 0 * * *'
  push:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  unlock-solarhealth-anomalies:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && contains(github.event.head_commit.message, 'SSM-257'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Unlock SolarHealth anomalies
        env:
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node scripts/unlock-solarhealth-anomalies.js
